### ISSUE TITLE
Currently getting an ambiguous method error in ReinforcementLearningCore v0.5.1

### ISSUE THREAD

**Issue by zsunberg** [JuliaReinforcementLearning/ReinforcementLearning.jl#171]
ERROR: LoadError: MethodError: update!(::ReinforcementLearningCore.CircularArrayBuffer{Int64,1}, ::SArray{Tuple{2},Int64,1,2}) is ambiguous. Candidates:
  update!(cb::ReinforcementLearningCore.CircularArrayBuffer{T,N}, data::AbstractArray) where {T, N} in ReinforcementLearningCore at /home/zach/.julia/packages/ReinforcementLearningCore/xwt8K/src/utils/circular_array_buffer.jl:167
  update!(cb::ReinforcementLearningCore.CircularArrayBuffer{T,1}, data) where T in ReinforcementLearningCore at /home/zach/.julia/packages/ReinforcementLearningCore/xwt8K/src/utils/circular_array_buffer.jl:172
Possible fix, define
  update!(::ReinforcementLearningCore.CircularArrayBuffer{T,1}, ::AbstractArray) where T

Didn't have time to check if this is fixed in ReinforcementLearningCore 0.6, but wanted to make sure it got reported.

**Comment by findmyway** [comment]
Thanks for reporting.

This should be correctly handled here now:

https://github.com/JuliaReinforcementLearning/CircularArrayBuffers.jl/blob/b40c98ed7a1e817a7c59265e772ffe7f2178bea4/src/CircularArrayBuffers.jl#L68

But here it seems you're pushing a `SArray{Tuple{2},Int64,1,2})` into a `CircularArrayBuffer{Int64,1}`. The behavior is still undefined. That's why you get the error above.

Either change the buffer of type `CircularArrayBuffer{Int64,1}` into `CircularArrayBuffer{Int}(2, capacity)`, which is of type  `CircularArrayBuffer{Int64,2}` (this is the most common case) or `CircularArrayBuffer{SArray{Tuple{2},Int64,1,2})}(capacity)`. The latter one will take the `SArray` as one element in the circular vector buffer.

**Comment by zsunberg** [comment]
Oh, right. Will fix the types when I pick this up again. Is there a way for the buffer to infer the correct types without requiring the user to specify? (the types did not match because I copied this from an example)

**Comment by findmyway** [comment]
> Will fix the types when I pick this up again. 

OK, let me know if you need any help. `ReinforcementLearningCore@v0.6` is not very stable right now. But the good news is that I get plenty of time to do a complete overhaul in the next two weeks. After that I'll tag a new release of `ReinforcementLearning.jl`.

> Is there a way for the buffer to infer the correct types without requiring the user to specify? 

Currently no. In the nutshell, it's just a wrapper of `Array`, so one may sacrifice the performance for convenience by using `Any` 😜

**Comment by zsunberg** [comment]
This worked once I got the types correct. Would be nice to have a mechanism for the buffer to default to the types appropriate for the environment.
