### ISSUE TITLE
TD3 Implementation

### ISSUE THREAD

**Issue by rcnlee** [JuliaReinforcementLearning/ReinforcementLearning.jl#174]
Hello,

TD3 is mentioned in the README, but I can't seem to find it anywhere in the source.  Is it implemented?

Along the same lines, I tried the `JuliaRL_TD3_Pendulum` experiment from the docs and it looks like it is missing:
```julia
julia> using ReinforcementLearning

julia> run(E`JuliaRL_TD3_Pendulum`)
ERROR: LoadError: MethodError: no method matching Experiment(::Val{:JuliaRL}, ::Val{:TD3}, ::Val{:Pendulum}, ::Nothing)
Closest candidates are:
  Experiment(::Any, ::Any, ::Any, ::Any, ::String) at /Users/rlee18/.julia/packages/ReinforcementLearningCore/xwt8K/src/core/experiment.jl:7
  Experiment(::Any, ::Any, ::Any, ::Any, ::Any) at /Users/rlee18/.julia/packages/ReinforcementLearningCore/xwt8K/src/core/experiment.jl:7
  Experiment(::Val{:JuliaRL}, ::Val{:DDPG}, ::Val{:Pendulum}, ::Nothing; save_dir, seed) at /Users/rlee18/.julia/packages/ReinforcementLearningZoo/uxBP8/src/experiments/rl_envs.jl:677
  ...
Stacktrace:
 [1] Experiment(::String) at /Users/rlee18/.julia/packages/ReinforcementLearningCore/xwt8K/src/core/experiment.jl:32
 [2] @E_cmd(::LineNumberNode, ::Module, ::Any) at /Users/rlee18/.julia/packages/ReinforcementLearningCore/xwt8K/src/core/experiment.jl:25
in expression starting at REPL[2]:1
```

Thanks!

**Comment by findmyway** [comment]
The experiment is here: https://github.com/JuliaReinforcementLearning/ReinforcementLearningZoo.jl/blob/master/src/experiments/rl_envs/JuliaRL_TD3_Pendulum.jl

And it's added since `ReinforcementLearningZoo@v0.2.0`.

My best guess is that you've installed an old version of ReinforcementLeaerning. This is most likely to happen if you install this package in the global Julia environment (often results in a downgraded installation). You can try `]add ReinforcementLearning#master` or create a temp dir and and `]activate .` there and try again.

**Comment by rcnlee** [comment]
You're right, my system seems to have a package dependency issue that has somehow restricted me to install an older version of the package.  Thanks!
