### ISSUE TITLE
PreActStage clarification

### ISSUE THREAD

**Issue by drozzy** [JuliaReinforcementLearning/ReinforcementLearning.jl#212]
In the [doc](https://juliareinforcementlearning.org/blog/an_introduction_to_reinforcement_learning_jl_design_implementations_thoughts/
) could you elaborate what you mean by the thing in the parenthesis: 
> update!(trajectory, policy, env, ::PreActStage, action) (The PreActStage is a little special, an extra action is already provided to avoid calculating it again.)

I'm not sure why this method exists (the one that takes `PreActStage`)

**Comment by findmyway** [comment]
This is one of the designs I'm not quite satisfied with. Let me explain it a little bit more here.

Since you know Acme well, I'll use some concepts (actor and learner) in it for analogy.

[**Assumption 1**] Generally speaking, in RL.jl an `AbstractPolicy` is considered to be an **actor**, which means `policy(env)` will not store the experience nor update the `policy` but only return an `action`.
[**Assumption 2**] If we want to update a `policy`, usually we wrap it in another type so we turn an **actor** into a **learner**. And the `Agent` is the most common one. (`learner` = `actor` + *experience*)
[**Assumption 3**?!] The lifetime of a **learner** is split into several stages for updating. **Nothing is returned from each stage**, we only do in-place updating of the `learner`.

Our current workflow for `Agent` is:

```
PreEpisodeStage -> policy(env) -> PreActStage -> env(action) -> PostActStage -> policy(env)  ... -> PostEpisodeStage
```

In `PreActStage` (or `PostActStage` if you prefer), we need to know the action to update the *experience* in the `policy` (that's the fourth argument in the `update!` function). Note that although we have passed both `policy` and `env` into that `update!` function, we can't use them to generate the action to update the *experience*. Because it might be different from the one returned from `policy(env)` step. 

Another approach is to merge the `policy(env)` step and `PreActStage` step into a single one. Then we need to break **Assumption 3** and the return must be an `action` to feed into `env`. In previous versions prior to v0.8, this approach is adopted.

None of them are perfect, but this is the best I can come up with now.

**Comment by drozzy** [comment]
Ok, I think that's how I understood it all along. It's just this documentation sentence threw me off: "The PreActStage is a little special, an extra action is already provided to avoid calculating it again."

I thought there was more to it. All you're saying is that `PreActStage` is an event that exists, and explaining why it exists. I would just remove that explanation lol, or move it above the whole list.

**Comment by drozzy** [comment]
Alternatively:

> update!(trajectory, policy, env, ::PreActStage, action) (The action here is the one selected by the policy to be executed on the env)

**Comment by findmyway** [comment]
> Alternatively:
> 
> > update!(trajectory, policy, env, ::PreActStage, action) (The action here is the one selected by the policy to be executed on the env)

Agree, this is much better.
