### ISSUE TITLE
Question: Clarification on the RL plots generated by the `run()` function

### ISSUE THREAD

**Issue by 00krishna** [JuliaReinforcementLearning/ReinforcementLearning.jl#357]
I worked through the basic tutorial for `ReinforcementLearning.jl` and it is definitely very helpful. I was just wondering if there is a good explanation of the plot that is generated by the `run()` function. I was not clear on what the axes were. Here is a picture of what I am talking about. 

![Selection_001](https://user-images.githubusercontent.com/2063593/125169708-695e1d00-e179-11eb-9f6c-3ff5e7b3f6e4.png)

There are just a few basic questions:

I understand that this is a random policy. The plot seems to show the final score for 10 successive runs of the policy.

1. What does the 10 episodes refer to? Does that refer to 10 iterations of the optimization algorithm--such as Value iterations, etc. Like I am I supposed to see the score converge to 1 as the iterations proceed? In a random policy I would see this bounce around, but for a policy that is learned I should see some convergence. 

2. I imagine that if I am using something like an epsilon greedy learner, that I would see some ups and downs in the plot as the learner explores the space. But then I would see some kind of gradual convergence towards the optimal score. Is that the right assumption. 

I can add a PR to explain some of this in the tutorial, but I just wanted to clarify for myself. Thanks.

**Comment by findmyway** [comment]
All are good questions. Let me answer them one by one.

> 1. What does the 10 episodes refer to? Does that refer to 10 iterations of the optimization algorithm--such as Value iterations, etc. Like I am I supposed to see the score converge to 1 as the iterations proceed? In a random policy I would see this bounce around, but for a policy that is learned I should see some convergence.

The **10 episodes** mean the `RandomPolicy()` has **interacted** with the `RandomWalk1D()` for 10 episodes. From the API designer's view, it's doesn't care whether there are optimizations that happened in these 10 episodes, not to say the number of optimization steps. But given that we used the `RandomPolicy()` above, we know there're no optimizations at all. So back to your question, no, it only means the policy played with the environment for 10 episodes not the 10 iterations of the optimization. And yes you'll see some convergence if you replace the random policy with some other learning methods (remember to wrap it in an `Agent` otherwise it's still running in the evaluation mode similar to the random policy).

> 2. I imagine that if I am using something like an epsilon greedy learner, that I would see some ups and downs in the plot as the learner explores the space. But then I would see some kind of gradual convergence towards the optimal score. Is that the right assumption.

Yes, you can compare the last two plots in the tutorial https://juliareinforcementlearning.org/docs/tutorial/

> I can add a PR to explain some of this in the tutorial, but I just wanted to clarify for myself. Thanks.

That's great! It would be helpful for others who are new to this package.
