### ISSUE TITLE
Params empty - no tracking

### ISSUE THREAD

**Issue by oysteinsolheim** [JuliaReinforcementLearning/ReinforcementLearning.jl#43]
Flux returns tracked Params:
    
```
julia> using Flux
julia> params(Dense(1, 1))
Params([Float32[-0.78894603] (tracked), Float32[0.0] (tracked)])
```

But when using ReinforcementLearning there is no longer tracking:

```
julia> using ReinforcementLearning
julia> params(Dense(1, 1))
Params([])
```

```
(v1.3) pkg> st
    Status `~/.julia/environments/v1.3/Project.toml`
  [c52e3926] Atom v0.11.1
  [6e4b80f9] BenchmarkTools v0.4.3
  [c5f51814] CUDAdrv v3.1.0
  [be33ccc6] CUDAnative v2.4.0
  [3a865a2d] CuArrays v1.2.1
  [587475ba] Flux v0.9.0
  [9ee9e592] IOLogging v0.2.0
  [b6b21f68] Ipopt v0.6.0
  [5fb14364] OhMyREPL v0.5.3
  [91a5bcdd] Plots v0.27.0
  [c36e90e8] PowerModels v0.13.0
  [158674fc] ReinforcementLearning v0.4.0 #master (https://github.com/JuliaReinforcementLearning/ReinforcementLearning.jl.git)
  [25e41dd2] ReinforcementLearningEnvironments v0.1.2
  [295af30f] Revise v2.2.2
  [2913bbd2] StatsBase v0.32.0
  [e88e6eb3] Zygote v0.3.4

```

**Comment by findmyway** [comment]
It seems that you are not following the install instructions provided [here](https://juliareinforcementlearning.org/ReinforcementLearning.jl/latest/#Installation-1). Although you are using the master branch of ReinforcementLearning.jl, that is not enough.

Let me explain it in detail. For now, we depend on the master branch of Flux(and it depends on the master of Zygote.jl IRTools.jl CuArrays.jl ZygoteRules.jl ). But simplely `] add ReinforcementLearning#master ` won't update these packages. To save your time, you can just use the environment(Project.toml and Manifest.toml) provided in the master branch. I know its annoying to do so. But before the next release of Flux, this is the best we can do. (Or you can use the Knet.jl backend)

As for your question here, the reason is that with Zygote.jl Flux no longer need the TrackedArray. So the Dense layer is just composed with normal Array now (override in ReinforcementLearning.jl), causing no params returned.

Given that we now support Knet.jl. It should be easy to support TrackedArray, but I'm not sure if it worth to do so(for some special functions it's really hard to write customizes back function).

I'm always glad to provide help if it is still not clear to you.

**Comment by oysteinsolheim** [comment]
Thanks for the feedback, I think I understand now. I had a new look at the code in neural_netowrk.jl and also found https://github.com/JuliaReinforcementLearning/ReinforcementLearning.jl/pull/38.
