### ISSUE TITLE
Donation

### ISSUE THREAD

**Issue by Mo8it** [JuliaReinforcementLearning/ReinforcementLearning.jl#595]
Hi @findmyway , I do really appreciate your work on this package. I did write my bachelor thesis using it and I want to thank you a lot. But the package deserves more love. I would like to donate to you as a way to say thanks and minimally support the development of this package.
Can you maybe add a link to the README to donate to you on https://liberapay.com/ for example? Liberapay is free open source software ;)

**Comment by Mo8it** [comment]
BTW, did you see this video about this package?
https://youtu.be/nefxM16lB_c

**Comment by findmyway** [comment]
> Hi @findmyway , I do really appreciate your work on this package. I did write my bachelor thesis using it and I want to thank you a lot. But the package deserves more love. I would like to donate to you as a way to say thanks and minimally support the development of this package. Can you maybe add a link to the README to donate to you on https://liberapay.com/ for example? Liberapay is free open source software ;)

Hey @Mo8it , I'm excited to hear that this package is used in your bachelor thesis. This really makes my day😄 !  Although I contributed a lot of code in the past, this package is a success from [many enthusiastic contributors](https://github.com/JuliaReinforcementLearning/ReinforcementLearning.jl#-contributors) and, needless to say, many awesome packages like Flux.jl, CUDA.jl and JuliaLang itself. And I think they need the support more than me ;) So let's consider sponsoring them continuously.

I also agree *this package deserves more love*. Due to some personal reasons, the development of this package is somewhat slowed down in the past half-year. The good news is that I'll join a startup focusing on RL in weeks. Hopefully, I'll bring some industry-level experiences into this package and make it available to more people. Let's wait and see.

> BTW, did you see this video about this package? https://youtu.be/nefxM16lB_c

No, I didn't. Actually this is the first time I hear people talking about this package in public. Thanks for sharing it. And I really appreciate their compliment 😆. By the way, I arranged an online meeting with [Julia-User-Group-Munich](https://www.meetup.com/Julia-User-Group-Munich/) to give an in-depth introduction to this package in the first week of May.
