### ISSUE TITLE
Definition of a policy

### ISSUE THREAD

**Issue by drozzy** [JuliaReinforcementLearning/ReinforcementLearning.jl#86]
Why is the policy defined as taking in the environment, and not just the state?

I always thought of it as: π(s) ⇒ a

**Comment by findmyway** [comment]
Actually, I've been thinking about this question on my way home from work.

In fact, the policy was just defined as you thought some time ago. `env |> observe |> π |> env`.  After the thoughtful discussions in https://github.com/JuliaReinforcementLearning/ReinforcementLearning.jl/issues/68 , I realized that the OpenAI/Gym style environment definition will bring in a lot of headaches.

Ideally, we want to separate policies and environments. A policy takes in an observation/state and returns an action. An environment takes in an action and returns the next observation, reward, isdone, and other meta info. Previously we created an `Observation` to store these data. It works fine until we want to generalize it to multi-agent environments and even simultaneous environments. In those cases, more and more info are needed to be put into the `meta` field. And in some cases, the state may have different representations, return them all in every interaction is too space wasteful. So I decided to adopt the async manner.  After interacting with the environment, nothing is returned, then a policy can fetch the next state manually or do something more complicated (like getting the history, or peak other players' private information, access the global shared score, etc )

Back to your question, I think adding an extra default function will resolve your confusion:

```julia
(p::AbstractPolicy)(env::AbstractEnv) = p(get_state(env))
```

So that new policies only needs to define `π(s) ⇒ a`.

**Comment by drozzy** [comment]
Maybe another component here could take a policy and env and apply one to the other to collect experience? Just seems like policy shouldn't care about how to call a specific env (whether it be a gym or something else).
On the other hand the way you have it now is easier to since there are less components - so I guess there are tradeoffs here as well.

https://github.com/deepmind/acme/blob/master/docs/index.md
![image](https://user-images.githubusercontent.com/140710/95618322-d0a83e80-0a3a-11eb-9478-5b8f68abfde9.png)

**Comment by findmyway** [comment]
The blocks in the agent is almost the same to the definition of Agent in ReinforcementLearningCore.jl except that we don't have the observe block explictly. 

Treating the agent as a policy is not that intuitive. And that's why I haven't decided to make agent as a subtype of AbstractPolicy yet.

If I were to design it again, I may have added the observe block too. My original thought was that it  is either a very simple layer of `get_state` or a very specific one which has little chance for reuse. So I simply decided to move this part into the inner part of policy. But thanks to multipe dispatch the code logic of this part is not coupled with other blocks.

**Comment by drozzy** [comment]
Sorry, I don't understand. In your short function here:
`(p::AbstractPolicy)(env::AbstractEnv) = p(get_state(env))`

Where does the function `get_state` come from?
Also, wouldn't it need to take an action as well? E.g. `get_state(env, action)`?

**Comment by findmyway** [comment]
Ah, sorry that `get_state` is renamed to `state` in the latest version.

https://github.com/JuliaReinforcementLearning/ReinforcementLearningBase.jl/blob/40820ec076a7328b9f5d5bc8ddaeff080a452484/src/interface.jl#L444-L454

**Comment by JohannesNaegele** [comment]
> 

Could you maybe give a concrete example, where these problems with `π(s)` for multi-agent environments arise? I am currently building my own (naive) RL library just for fun and I don't really see the issue with this approach yet...
